In [ ]:
'''案例：
        创建指定类型的张量。

涉及到的函数：
        type(torch支持的数据类型)
        half()/double()/float()/short()/int()/long()

掌握的函数：
        type（）
'''


In [1]:
# 导包
import torch
# 场景一 ：直接创建指定类型的张量.
t1= torch.tensor([1,2,3,4,5],dtype=torch.float) #默认是：float32
print(f't1:{t1},(元素)类型:{t1.dtype},(张量)类型:{type(t1)}')

t1:tensor([1., 2., 3., 4., 5.]),(元素)类型:torch.float32,(张量)类型:<class 'torch.Tensor'>


In [2]:
# 创建好张量后  ->  做类型转换
# 思路1 ： type函数（） 推荐掌握

t2= t1.type(torch.int32)
print(f't2:{t2},(元素)类型:{t2.dtype},(张量)类型:{type(t2)}')

t2:tensor([1, 2, 3, 4, 5], dtype=torch.int32),(元素)类型:torch.int32,(张量)类型:<class 'torch.Tensor'>


In [3]:
# 思路2 ： half()/double()/float()/short()/int()/long()

print(t2.half())   #float16
print(t2.float())   #float32，默认
print(t2.double())   #float64
print(t2.short())   #int16
print(t2.int())   #int32
print(t2.long())   #int64，默认

tensor([1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([1., 2., 3., 4., 5.])
tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
tensor([1, 2, 3, 4, 5], dtype=torch.int16)
tensor([1, 2, 3, 4, 5], dtype=torch.int32)
tensor([1, 2, 3, 4, 5])


## 总结

### 1.创建张量的方式

In [ ]:
# torch.tensor()

# torch.Tensor()

# torch.intTensor()
# torch.floatTensor()

### 2.创建线性和随机张量

In [5]:
# arange（） ，linspace(),

# initial_seed()--> 时间戳
# manual_seed() --> 指定随机种子

# rand(),randn(),randint()

### 3.创建 0、1、指定值张量

In [ ]:
# torch.zeros(),torch.zeros_like()

# torch.ones(),torch.ones_like()

# torch.full(),torch.full_like()

#### 4. 张量元素类型转换

In [ ]:
#type()
#
# half(),float(),double() float16,32,64

#short(),int(),long() int16,32,64